services:
  mongodb:
    image: mongodb/mongodb-atlas-local:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - mongodb_mongot:/data/mongot
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=
      - MONGODB_INITDB_ROOT_PASSWORD=
    healthcheck:
      test: mongosh --eval "db.runCommand('ping').ok"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongodb_data:
  mongodb_config:
  mongodb_mongot:
  redis_data:
  uploads_data:
