"""Tests that correlation_id threads from handler through to run_inference."""

from unittest.mock import AsyncMock
import pytest

from backend.database import connect_db, disconnect_db, get_db
from backend.modules.chat._repository import ChatRepository


@pytest.fixture
async def repo(clean_db):
    await connect_db()
    r = ChatRepository(get_db())
    await r.create_indexes()
    yield r
    await disconnect_db()


@pytest.mark.asyncio
async def test_handle_chat_send_passes_correlation_id_to_run_inference(repo, monkeypatch):
    """The correlation_id from the client (or generated by the handler) must be
    forwarded to run_inference so all stream events use the same id."""
    captured = {}

    async def fake_run_inference(
        user_id, session_id, repo_arg, session_arg, *, connection_id=None, correlation_id=None
    ):
        captured["correlation_id"] = correlation_id

    class FakeBus:
        async def publish(self, event_type, event, *, scope, target_user_ids, correlation_id):
            pass

    monkeypatch.setattr("backend.modules.chat._handlers_ws.get_event_bus", lambda: FakeBus())
    monkeypatch.setattr("backend.modules.chat._handlers_ws.run_inference", fake_run_inference)
    monkeypatch.setattr("backend.modules.chat._handlers_ws.cancel_all_for_user", AsyncMock(return_value=0))
    monkeypatch.setattr("backend.modules.chat._handlers_ws.track_extraction_trigger", AsyncMock())
    monkeypatch.setattr("backend.modules.chat._handlers_ws.get_db", lambda: get_db())

    session = await repo.create_session("user1", "persona1")
    session_id = session["_id"]

    from backend.modules.chat._handlers_ws import handle_chat_send
    await handle_chat_send("user1", {
        "session_id": session_id,
        "content": [{"type": "text", "text": "hi"}],
        "correlation_id": "client-id-abc",
    })

    assert captured.get("correlation_id") == "client-id-abc"


@pytest.mark.asyncio
async def test_handle_chat_regenerate_passes_correlation_id_to_run_inference(repo, monkeypatch):
    """Same thing for chat.regenerate."""
    captured = {}

    async def fake_run_inference(
        user_id, session_id, repo_arg, session_arg, *, connection_id=None, correlation_id=None
    ):
        captured["correlation_id"] = correlation_id

    class FakeBus:
        async def publish(self, event_type, event, **kwargs):
            pass

    monkeypatch.setattr("backend.modules.chat._handlers_ws.get_event_bus", lambda: FakeBus())
    monkeypatch.setattr("backend.modules.chat._handlers_ws.run_inference", fake_run_inference)
    monkeypatch.setattr("backend.modules.chat._handlers_ws.cancel_all_for_user", AsyncMock(return_value=0))
    monkeypatch.setattr("backend.modules.chat._handlers_ws.get_db", lambda: get_db())

    session = await repo.create_session("user1", "persona1")
    session_id = session["_id"]
    # Need a last user message for regenerate to proceed
    await repo.save_message(session_id, role="user", content="hi", token_count=1, user_id="user1")

    from backend.modules.chat._handlers_ws import handle_chat_regenerate
    await handle_chat_regenerate("user1", {
        "session_id": session_id,
        "correlation_id": "client-id-regen",
    })

    assert captured.get("correlation_id") == "client-id-regen"
