import { useNotificationStore } from "../store/notificationStore"
import { useChatStore } from "../store/chatStore"
import { useConversationModeStore } from "../../features/voice/stores/conversationModeStore"
import { initInstallPrompt } from "./installPrompt"

const SETTLE_MS = 500

/**
 * Reload the page as soon as both the chat stream and Conversational Mode
 * are idle. If both are already idle, reload immediately. The caller owns
 * the actual reload action (`doReload`) so tests can inject a spy.
 *
 * Exported for unit testing.
 */
export function reloadWhenIdle(doReload: () => void): void {
  const isBusy = () =>
    useChatStore.getState().isStreaming ||
    useConversationModeStore.getState().active

  if (!isBusy()) {
    doReload()
    return
  }

  let settleTimer: ReturnType<typeof setTimeout> | null = null

  const clearSettle = () => {
    if (settleTimer !== null) {
      clearTimeout(settleTimer)
      settleTimer = null
    }
  }

  const tryScheduleReload = () => {
    if (isBusy()) {
      clearSettle()
      return
    }
    clearSettle()
    settleTimer = setTimeout(() => {
      if (!isBusy()) {
        unsubChat()
        unsubConversation()
        doReload()
      }
    }, SETTLE_MS)
  }

  const unsubChat = useChatStore.subscribe(tryScheduleReload)
  const unsubConversation = useConversationModeStore.subscribe(tryScheduleReload)
}

/**
 * Registers the service worker generated by vite-plugin-pwa.
 *
 * Only runs in production builds — the dev server intentionally has no
 * service worker so Vite HMR keeps working and stale caches don't confuse
 * local development.
 *
 * On update: reload automatically. If the user is in Conversational Mode
 * or an LLM response is streaming, the reload is deferred until both are
 * idle for 500ms (no timeout — the reload waits as long as needed).
 */
export function registerPwa(): void {
  initInstallPrompt()

  if (!import.meta.env.PROD) return

  void import("virtual:pwa-register").then(({ registerSW }) => {
    const updateSW = registerSW({
      onNeedRefresh() {
        // Activate the waiting service worker, then reload when idle.
        void updateSW(true)
        reloadWhenIdle(() => window.location.reload())
      },
      onOfflineReady() {
        useNotificationStore.getState().addNotification({
          level: "success",
          title: "Offline ready",
          message: "Chatsune is now available offline.",
        })
      },
    })
  })
}
