import { useNotificationStore } from "../store/notificationStore"
import { initInstallPrompt } from "./installPrompt"

/**
 * Registers the service worker generated by vite-plugin-pwa and wires its
 * lifecycle events into Chatsune's toast system.
 *
 * Only runs in production builds — the dev server intentionally has no
 * service worker so Vite HMR keeps working and stale caches don't confuse
 * local development.
 */
export function registerPwa(): void {
  initInstallPrompt()

  if (!import.meta.env.PROD) return

  // Dynamic import so the virtual module is only pulled in for production
  // builds and doesn't trip up tests or the dev server.
  void import("virtual:pwa-register").then(({ registerSW }) => {
    const updateSW = registerSW({
      onNeedRefresh() {
        useNotificationStore.getState().addNotification({
          level: "info",
          title: "Update verfügbar",
          message: "Eine neue Version von Chatsune ist bereit.",
          // Keep the update toast on-screen until the user acts on it.
          duration: 60 * 60 * 1000,
          action: {
            label: "Neu laden",
            onClick: () => {
              void updateSW(true)
            },
          },
        })
      },
      onOfflineReady() {
        useNotificationStore.getState().addNotification({
          level: "success",
          title: "Offline bereit",
          message: "Chatsune ist jetzt auch offline verfügbar.",
        })
      },
    })
  })
}
