class Topics:
    USER_CREATED = "user.created"
    USER_UPDATED = "user.updated"
    USER_DEACTIVATED = "user.deactivated"
    USER_PASSWORD_RESET = "user.password_reset"
    AUDIT_LOGGED = "audit.logged"
    ERROR = "error"
    PERSONA_CREATED = "persona.created"
    PERSONA_UPDATED = "persona.updated"
    PERSONA_DELETED = "persona.deleted"
    LLM_CREDENTIAL_SET = "llm.credential.set"
    LLM_CREDENTIAL_REMOVED = "llm.credential.removed"
    LLM_CREDENTIAL_TESTED = "llm.credential.tested"
