"""Internal event models for the LLM adapter streaming layer.

These types represent the normalised stream of events that any provider adapter
may emit. Consumers (e.g. the chat module) receive a ``ProviderStreamEvent``
and dispatch on the concrete type.
"""

from pydantic import BaseModel


class ContentDelta(BaseModel):
    """A fragment of generated text content."""

    delta: str


class ThinkingDelta(BaseModel):
    """A fragment of the model's internal reasoning / thinking step."""

    delta: str


class ToolCallEvent(BaseModel):
    """A tool call emitted by the model during a streaming response."""

    id: str       # synthetic ID generated by the adapter
    name: str
    arguments: str  # JSON-encoded argument object


class StreamDone(BaseModel):
    """Signals the end of a successful stream, with optional token-usage data."""

    input_tokens: int | None = None
    output_tokens: int | None = None


class StreamError(BaseModel):
    """A terminal error from the upstream provider."""

    # Normalised error codes understood by all consumers:
    #   "invalid_api_key"      — authentication failure
    #   "provider_unavailable" — upstream is down or unreachable
    #   "model_not_found"      — requested model does not exist on the provider
    error_code: str
    message: str


# Union type used as the return type for adapter stream generators.
ProviderStreamEvent = ContentDelta | ThinkingDelta | ToolCallEvent | StreamDone | StreamError
